### PR TITLE
Pass tree root via constructor

### PR DESCRIPTION
**Pull request by elonmir**
Should fix the deprecations thrown by symfony

### CODE REVIEW

**Comment by DZunke** [comment]
Hey... Thanks @elonmir but there is a problem with the target. The constructor was added with symfony 4.2. So if we get it merged in the 3.x branch it will not work with symfony 3.x but only with symfony >= 4.2 (also not 4.0 or 4.1). 

I think a possibility would be to create an 4.x branch with 4.x version tree and edit the composer.json to not support anything beneath symfony 4.2. In this case the travis config should be updated too cause as you can see at your test run the 3.x version of symfony is failing. 😉 

What do you think about the new branch and version tree?

**Comment by elonmir** [comment]
Seems reasonable.

Yeah, you are right, the changes for the configuration constructor were added in 4.2.

I cherry picked your latest commit, so test should work fine now.

**Comment by DZunke** [comment]
And finally there is a test to fail with symfony 4 styling config 😉

**Comment by DZunke** [comment]
Thanks @elonmir. This is now part of the new 4.x tree which is for symfony 4 and beyond

**Pull request merged**
